# Required items.
game: Doom Eternal
api: 1
steamID: 782330
uid: com.thegreatcabbage.doometernal
author: TheGreatCabbage
packageName: doometernal
features:
  - keymaps

# Optional items.
keymapConfig: C:\Users\$!USERNAME!$\Saved Games\id Software\DOOMEternal\base\DOOMEternalConfig.cfg

gameDirectory: DOOMEternal
verificationPaths:
  - DOOMEternalx64vk.exe